version: '3.8'
services:
  # App Service
  app:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    depends_on: 
      - mongodb
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - common-net

  mongodb:
    image: mongo:4.4.0
    ports:
      - 27017:27017
    volumes:
      - mongo_vol:/data/db
    networks:
       - common-net

volumes:
  mongo_vol:

networks:
  common-net:
    driver: bridge
